name: Deploy to S3

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Vite 요구사항

      - name: Install dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Upload with aws-actions/s3-sync
        uses: aws-actions/s3-sync@v1
        with:
          bucket: momssi-app
          region: ap-northeast-2
          source-dir: dist
          destination-dir: app
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ETZM8HOT38J5F \
            --paths "/app/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2